### ISSUE TITLE
targetPath issue

### ISSUE THREAD

**Issue by zawilliams** [backflip/gulp-iconfont-css#16]
I think I've got the `path`, `targetPath` and `fontPath` configured correctly, but I'm having an issue now with `targetPath`.

I'm working on a Laravel app and have my gulpfile located in the project root. So my directory structure looks like:
- /app
- /public
- gulpfile.js

My gulp configuration code for this plugin is as follows:

```
var fontName = 'icons';

gulp.task('icon-font', function(){
    gulp.src(['app/assets/icons/*.svg'])
        .pipe(iconfontcss({
            fontName: fontName,
            path: 'app/assets/scss/templates/_icons.scss',
            targetPath: '../../../app/assets/scss/components/_icons.scss',
            fontPath: '../fonts/'
        }))
        .pipe(iconfont({
            fontName: fontName
        }))
        .pipe(gulp.dest('public/assets/fonts/'));
});
```

The problem I'm running into is this: the `targetPath` is supposed to go into `app/assets/scss/components/` but its going into `public/assets/scss/components` instead. It's like "app" is being replaced by "public" in the path.

Am I doing something wrong or is this an issue with the plugin?

**Comment by Iuriy-Budnikov** [comment]
Option base not works for me.
gulp 3.9.0

Issue still is open.

**Comment by backflip** [comment]
Hey Iuriy,
could you save your Gulpfile to https://gist.github.com so I can try to reproduce it?

**Comment by benifbond** [comment]
How can I resolve this problem ? 
The targetPath creates a subfolder inside the fonts folder that comprises the full working path inside the fonts director.
For example:
fonts/
	Users/username/full project path/icons.scss.

 The problem occurs in MacOs and Linux. I do not desire to have either additional folders created or _icons.scss.
