### ISSUE TITLE
html template

### ISSUE THREAD

**Issue by peter-mouland** [backflip/gulp-iconfont-css#23]
If i created a way for this plug to also generate an html template, would you accept it?

my first attempt i fear is not good enough (simply adding `|html` [#L33](https://github.com/backflip/gulp-iconfont-css/blob/master/index.js#L33)) as you have to call `iconfontCSS` twice in your gulpFile (along with `iconFont` twice).

my second attempt was to create a `htmlTemplate` config option, but this meant i used a global streamConfig to get around a closure problem with streams, plus the output was only ever a single file rather than the chosen extension and a html file.

Do you know how to create and save 2 separate streams or this against how gulp should work?

**Comment by amcdnl** [comment]
@backflip Would you mind sharing your template you use above?

**Comment by backflip** [comment]
@amcdnl You should be able to reuse any template here: https://github.com/backflip/gulp-iconfont-css/tree/master/templates

I'm mostly using https://github.com/unic/estatico/blob/develop/source/assets/css/templates/_iconfont.scss (based on Handlebars).
