### ISSUE TITLE
When using `gulp-iconfont` with `gulp-iconfont-css`, the `prependUnicode` config is not working.

### ISSUE THREAD

**Issue by lzl124631x** [backflip/gulp-iconfont-css#40]
please see details in [gulp-iconfont issue #123](https://github.com/nfroidure/gulp-iconfont/issues/123)

**Comment by backflip** [comment]
> gulp-iconfont-css didn't prepend unicode to filename in my case. Do you mean that gulp-iconfont-css will prepend unicode to filename by default? The readme doesn't say anything about it, nor does gulp-iconfont-css provide an option for prependUnicode.

It does so in the virtual files being passed to `gulp-iconfont` (this is necessary in order for `gulp-iconfont` to use the same codepoints `gulp-iconfont-css` already inserted into generated CSS).

What does `gulp-iconfont` do exactly when setting `prependUnicode`? And what do you want to achieve with this?

**Comment by lzl124631x** [comment]
@backflip Updated repo <https://github.com/lzl124631x/iconfont-bug> with two gulp commands, `iconfont-with-css` and `iconfont-without-css`.

You can first run `iconfont-with-css` and will see the files in input folder unaltered.

Then run `iconfont-without-css`, the `account-o.svg` in input folder is renamed to `uEA01-account-o.svg`.

That's what the `prependUnicode` means -- prepending the unicode to the original svg file.

This setting is useful in cases that you want to keep the unicode mapping **unchanged** when you add a new svg file or rename a existing svg file, so your existing css files that use the unicodes won't break.

---

With that said, I think a more effective way to avoid conflicts between different versions of font files is **adding timestamp to css files**. That's what [pr 40](https://github.com/backflip/gulp-iconfont-css/pull/39) is for.

**Comment by backflip** [comment]
I see, thanks for clarifying! 
Unfortunately, I can't think of a reasonable solution rather than not using this plugin but relying on the `glyphs` event of `gulp-iconfont` and generating the CSS on your own: https://github.com/nfroidure/gulp-iconfont#make-your-css

**Comment by jefsnare** [comment]
@backflip Should we close this one?

**Comment by rtransat** [comment]
How to make the CSS with Gulp 4?
