### ISSUE TITLE
Add support for some kind of aliasing

### ISSUE THREAD

**Issue by watzon** [backflip/gulp-iconfont-css#41]
Not quite sure how this would work, but for now the only way to create aliases for icons is to duplicate the icon, which as we all know is not very maintainable. It would be nice if we could somehow define that an icon has an alias so that in the outputted CSS the icons have the same content

**Comment by bradrisse** [comment]
I have created a pull request to do what your asking. https://github.com/backflip/gulp-iconfont-css/pull/57

Basically you add an object array and pass it into options `var aliases = {github: ['git']}`

**Comment by backflip** [comment]
@bradrisse's PR was just published with 2.3.0
