### ISSUE TITLE
Reserved Words

### ISSUE THREAD

**Issue by evansantos** [backflip/gulp-iconfont-css#45]
Hi, @backflip 
Do you have a list of reserved words? Because I've tried to use **_equal.svg_** and it had messed up with my iconset

![cry](http://i.giphy.com/xTk9ZOLgUNKlF82JvW.gif =256)

**Comment by backflip** [comment]
@evansantos, what do you mean by "messed up"?

**Comment by backflip** [comment]
Closed due to inactivity. Feel free to reopen if necessary!
