### ISSUE TITLE
Allow path and targetPath to be absolute

### ISSUE THREAD

**Issue by watzon** [backflip/gulp-iconfont-css#47]

**Comment by sarahdayan** [comment]
Hey! Any chance this is done soon? Thanks for the great work!

**Comment by elboletaire** [comment]
Please... this is really necessary. I'm having issues with my deployment due to how the targetPath is being treaty... 

Allowing us to define absolute paths will do the trick.

**Comment by yakuthemes** [comment]
gosh this is so fustrating...

**Comment by backflip** [comment]
@yakuthemes, I agree. :) Please provide a test case since I don't understand the problem yet.

**Comment by backflip** [comment]
Closed due to missing feedback
