### ISSUE TITLE
Icon selector in simple way

### ISSUE THREAD

**Issue by Draeli** [backflip/gulp-iconfont-css#50]
Actually, it's necessary to write ".icon .icon-nameoficon" inside class attribute but why not to use this selector :
```
[class^="icon-"],
[class*=" icon-"]{...}
```
with this, it's only necessary to use ".icon-nameoficon".

**Comment by liova** [comment]
in the template .css .scss and .less :+1: 

` [class^="<%= cssClass %>-"]:before, [class*=" <%= cssClass %>-"]:before {`

**Comment by backflip** [comment]
@Draeli, thanks for your input! However, this very much depends on the CSS "architecture" you are relying on. Since approaches like BEM are very widespread and would roughly correspond to what we are doing here, I think we can keep the template as it is. You can always overwrite it anyway.
