### ISSUE TITLE
Don't run if font not changed

### ISSUE THREAD

**Issue by dlishtvan** [backflip/gulp-iconfont-css#55]
Hi. I have a problem with     gulp-iconfont,  gulp-iconfont-css'. How I can check if font changed? I try use 'gulp-changed' - but still don't work. Font generate(( Can somebody help me?

**Comment by backflip** [comment]
@dlishtvan, could you post your complete gulp task?

**Comment by backflip** [comment]
Closed due to inactivity. Feel free to reopen if necessary!
