### ISSUE TITLE
Icon created conflict with emoji on iphone

### ISSUE THREAD

**Issue by gauravr7** [backflip/gulp-iconfont-css#58]
Using icon css from this cause issue on iphone.

1. When new font is added whole fonts are mismatched.
2. Fonts on iphone are replaced by random emojis on iphone.

Any possible solution to fix this.

Thanks

**Comment by backflip** [comment]
Hey @gauravr7,
I'd need more information to help debug. Is there a URL I can check out?

**Comment by gauravr7** [comment]
Hi @backflip,
No there is no public url available to test it out atm.

But I found something that is exactly related to this:

1. https://www.etsy.com/teams/7720/bugs/discuss/14559563/page/1
2. https://twitter.com/grigs/status/668182333242011648

**Comment by backflip** [comment]
I have no chance of debugging this without a public URL

**Comment by kanivets** [comment]
In iOS, before icon font been loaded (better to reproduce on slow network), there are emoji instead of icons. After fonts loaded everything looks fine (icons replaced emoji). Is it possible to fix this issue?
