### ISSUE TITLE
Prototype pollution vulnerability with dependency of lodash @ under 4.17.5

### ISSUE THREAD

**Issue by peco-pc** [backflip/gulp-iconfont-css#62]
With the update of npm@6, the packages which have vulnerabilities are shown with the command `npm audit`.
This package has a dependency of lodash@3.10.1, which has a vulnerability of prototype pollution.
https://nodesecurity.io/advisories/577
There might be more dependencies with vulnerability, I didn't inspect.
Please update them.

**Comment by jefsnare** [comment]
@backflip is this solved in #61

**Comment by backflip** [comment]
@jefsnare, mostly with https://github.com/backflip/gulp-iconfont-css/pull/64.
Thanks for the pointer, @peco-pc
