### ISSUE TITLE
Ability to for the mixins and function to be seperate from the font-face declaration and icon classes

### ISSUE THREAD

**Issue by jjbert18** [backflip/gulp-iconfont-css#68]
I am running into a issue with having the mixins, function, font-face, and classes all in one file. The issue is that in a component based architecture the mixin and function need to be available for usage on any stylesheet. Importing the icon stylesheet everywhere allows the mixins to work properly but causes the font-face declaration and icon classes to be printed on every components stylesheet when those only need to be printed once in a base stylesheet.

A possible solution is to have the mixins and function in a separate file from the font-face declaration and icon classes so a user can set up their imports to use the mixin globally and without the duplicated font-face and classes.

Any help is appreciated. At this moment I am not sure how to create the separate files with a custom template.

Thank you

**Comment by backflip** [comment]
@jjbert18, one approach would be to replace the default `scss` template not to render classes but give you a sass map of icons instead. 

Before (see https://github.com/backflip/gulp-iconfont-css/blob/master/templates/_icons.scss#L48-L51):
```
...

<% _.each(glyphs, function(glyph) { %>.<%= cssClass%>-<%= glyph.fileName %> {
	@include <%= cssClass%>(<%= glyph.originalFileName ? glyph.originalFileName : glyph.fileName %>);
}
<% }); %>
```


After:
```
...

$icons: (
	<% _.each(glyphs, function(glyph) { %>
		<%= glyph.fileName %>: <%= glyph.originalFileName ? glyph.originalFileName : glyph.fileName %>,
	<% }); %>
);
```

With the demo data in `test/`, this would generate the following block:
```
$icons: (
	github: github,
	git: github,
	twitter: twitter,
);
```

Then wherever you want to render icon classes, you use your own sass loop:
```
@each $key, $name in $icons {
	.icon-#{$key} {
		@include icon(name);
	}
}
```

**Comment by jjbert18** [comment]
@backflip Thank you for the great help setting up the map! 

In addition to your code I wrapped the `@font-face {...}` in a mixin and included it next to the `@each` for the icon classes on the sites base stylesheet. This allowed the generated icons file to be imported as needed to allow the mixins to be used on any file and the font-face and classes added only once.

**Mixin:**
`
@mixin icon-font-face() {
  @font-face {
    font-family: "<%= fontName %>";
    src: url('<%= fontPath %><%= fontName %>.eot<%= cacheBusterQueryString %>');
    src: url('<%= fontPath %><%= fontName %>.eot?<%= cacheBuster %>#iefix') format('eot'),
    url('<%= fontPath %><%= fontName %>.woff2<%= cacheBusterQueryString %>') format('woff2'),
    url('<%= fontPath %><%= fontName %>.woff<%= cacheBusterQueryString %>') format('woff'),
    url('<%= fontPath %><%= fontName %>.ttf<%= cacheBusterQueryString %>') format('truetype'),
    url('<%= fontPath %><%= fontName %>.svg<%= cacheBusterQueryString %>#<%= fontName %>') format('svg');
  }
}
`

**On the sites base stylesheet:**
`
@include icon-font-face();

@each $key, $name in $icons {
  .icon-#{$key} {
    @include icon($name);
  }
}
`
