### ISSUE TITLE
iOS - emoji in place of icons, while icon font loading

### ISSUE THREAD

**Issue by kanivets** [backflip/gulp-iconfont-css#69]
In iOS, before icon font been loaded (better to reproduce on slow network), there are emoji instead of icons. After fonts loaded everything looks fine (icons replaced emoji). Is it possible to fix this issue?

**Comment by backflip** [comment]
@kanivets, could you share your complete setup? Sounds like the icons are not mapped to a `Unicode private use area` (see https://github.com/nfroidure/gulp-svgicons2svgfont#optionsstartunicode).

**Comment by kanivets** [comment]
@backflip  It works, thanks  a lot for help!
