### ISSUE TITLE
Adding new icons then build issue

### ISSUE THREAD

**Issue by muhamed87** [backflip/gulp-iconfont-css#71]
Hi all,

I'm excited with that plugin and I'm already using it, but I faced a problem that when adding new SVG icons to the folder, the current css that generated on build gets changed after building to get the new icons, and the icons content code is changed.

Is anyone faced the same issue, and how we can solve it?

**Comment by backflip** [comment]
@muhamed87, you can use the `fixedCodepoint` option to map icons to specific chars: https://github.com/backflip/gulp-iconfont-css/blob/ef1af81a0e5c7bcacc57a1cb1c95ae8b16214484/test/main.js#L104-L107

**Comment by muhamed87** [comment]
That not solve my issue as I have about more than 100 icons and I can't add all icons manually in the fixedCodePoint option

**Comment by backflip** [comment]
I'm afraid there is no other solution. You could create the list dynamically, e.g. by sorting the icons by their modified date: https://stackoverflow.com/a/10559790/661112

**Comment by muhamed87** [comment]
Thanks for your replies, I thought about the last solution but sometimes icons may be updated, so that will not solve the problem as the icon will then get another code.

I'm trying to create a json file and save icons with the code created for each icon, then when adding new icons it should be added to the latest of the json array and get new code, then building the icon font css file.

**Comment by backflip** [comment]
Sounds reasonable. 👍
